# Generated by Django 5.0.1 on 2024-04-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_preparation_time_recipe_servigs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='titel',
            new_name='title',
        ),
    ]
