# Generated by Django 5.0.1 on 2024-04-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_titel_recipe_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='descreption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='is_publeshed',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='preparatio_steps',
            new_name='preparation_steps',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='preparatio_steps_is_html',
            new_name='preparation_steps_is_html',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='servigs',
            new_name='servings',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='servigs_unit',
            new_name='servings_unit',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
